services:
  traefik:
    image: traefik:v3.1
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./letsencrypt:/letsencrypt"
  app:
    image: "ghcr.io/bentrynning/hosty:main"
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.rule=Host(`hostii.dev`)
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.app.tls=true
  # backend:
  #   image: "ghcr.io/bentrynning/hosty:main"
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.backend.entrypoints=websecure
  #     - traefik.http.routers.backend.rule=Host(`backend.hostii.dev`)
  #     - traefik.http.routers.backend.tls.certresolver=letsencrypt
  #     - traefik.http.routers.backend.tls=true 