services:
  traefik:
    image: traefik:v3.1
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./letsencrypt:/letsencrypt"
  app:
    image: "ghcr.io/bentrynning/hosty:main"
    labels:
      - traefik.enable=true
      - traefik.http.routers.hosty.entrypoints=websecure
      - traefik.http.routers.hosty.rule=Host(`hostii.dev`)
      - traefik.http.routers.hosty.tls.certresolver=letsencrypt
      - traefik.http.routers.hosty.tls=true

   