# This workflow creates a tar.gz archive of the engine package and uploads it as a release asset.
name: Release Engine Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-engine-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get engine version
        id: get_version
        run: |
          cd packages/engine
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "Engine version: v$VERSION"

      - name: Create engine-latest.tar.gz
        run: |
          cd packages
          tar -czf engine-latest.tar.gz engine
          mv engine-latest.tar.gz $GITHUB_WORKSPACE

      - name: Upload engine-latest.tar.gz as artifact
        uses: actions/upload-artifact@v4
        with:
          name: engine-latest
          path: engine-latest.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: engine-latest.tar.gz
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Engine Release ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
